version: '3.8'

services:

    db:
      image: postgres:16.1
      container_name: db-ranking
      restart: always
      volumes:
        - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
        - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      environment:
        POSTGRES_DB: 'ranking'
        POSTGRES_USER: 'serviceranking'
        POSTGRES_PASSWORD: 'ranking2025@'
      ports:
        - '5433:5432'