spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/junnior123456/config-repo.git
          clone-on-start: true

server:
  port: 7777

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: "${spring.application.name}:${random.value}"