spring:
  application:
    name: report-ms
  config:
    import: "configserver:http://localhost:7777"

server:
  port: 7070
  servlet:
    context-path: /report-ms

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
